## Unix specific compiler selector macro. Takes identifier as given in compilers.cmake.
## e.g. needs the variables "CONTRIB;QT;GENERATOR" to be defined and prefixed by VSVersion_Architecture_
## set(VS10_x64_CONTRIB "C:/dev/contrib_vs10_64bit")

macro(select_vs_version version arch)
	set(vs_variables "CONTRIB;QT;GENERATOR")
	set(compiler_prefix "${version}_${arch}")
  foreach(vs_var IN LISTS vs_variables)
    if(DEFINED ${compiler_prefix}_${vs_var})
      if(TEST_MACROS_DEBUG)
        safe_message("Setting ${vs_var} -> ${${compiler_prefix}_${vs_var}}")        
      endif(TEST_MACROS_DEBUG)
      set( ${vs_var} "${${compiler_prefix}_${vs_var}}")
      set( COMPILER_IDENTIFIER "${compiler_prefix}")
    else()
      safe_message(FATAL_ERROR "No compiler ${compiler_prefix} found")
    endif()
  endforeach()
	
	set(arch_variables "MYRIMATCH_PATH;OMSSA_PATH;XTANDEM_PATH;FIDO_PATH")
	foreach(arch_var IN LISTS arch_variables)
		if(DEFINED ${arch}_${arch_var})
			set( ${arch_var} "${${arch}_${arch_var}}")
		else()
			safe_message(FATAL_ERROR "Missing ${arch_var} for architecture ${arch}")
		endif()
	endforeach()
endmacro()
