#!/bin/bash

XVNC=Xvnc

if [ ! -n "$1" ]
then
  echo "Usage: `basename $0` {start|stop|restart} [DISPLAY]"
fi

if [ ! -n "$2" ]
then
  DISPLAY_NUMBER=$RANDOM
  let "DISPLAY_NUMBER %= 89"
  let "DISPLAY_NUMBER += 12" # avoid 0-11
else
  DISPLAY_NUMBER=$2
fi

XVFBARGS=":$DISPLAY_NUMBER"
PIDFILE="/tmp/.X${DISPLAY_NUMBER}-lock"
case "$1" in
  start)
    #echo -n "Starting Xvnc .. "
    #x11vnc requires the create and display option
    #$XVNC -xvnc || echo "Does not support -create. Hope that a server is running."
    #$XVNC -listdpy || echo "No listing possible"
    (vncserver $XVFBARGS || $XVNC -passwd "OpenMS" -xvnc -display $XVFBARGS) &
    echo "done"
    ;;
  stop)
    #echo -n "Killing Xvnc .. " 
    XVNCPID=$(cat $PIDFILE)
    kill $XVNCPID
    #echo "done"
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    exit 1
esac
echo $DISPLAY_NUMBER
exit 0
