if(NOT DEFINED TEST_MACROS_INCLUDED)
  include(${SCRIPT_PATH}/test_macros.cmake)
endif()

# Check for required variables.
set(required_variables "CTEST_SOURCE_DIRECTORY;CTEST_BINARY_DIRECTORY;INITIAL_CACHE;CTEST_BUILD_NAME")

backup_and_check_variables(required_variables)

## external project:
SET (CTEST_SOURCE_TESTEXTERNAL_DIRECTORY "${CTEST_SOURCE_DIRECTORY}/src/tests/external/")
SET (CTEST_BINARY_TESTEXTERNAL_DIRECTORY "${CTEST_BINARY_DIRECTORY}/source/TEST/EXTERNAL/")

SET (CTEST_ENVIRONMENT "OPENMS_BUILD_TREE=${CTEST_BINARY_DIRECTORY}")

## extend initial cache with references to
## the OpenMS directory
SET(INITIAL_CACHE "${INITIAL_CACHE}
")

## (re)define build name and test directories
SET (CTEST_BUILD_NAME "${CTEST_BUILD_NAME}_External")
SET (CTEST_SOURCE_DIRECTORY ${CTEST_SOURCE_TESTEXTERNAL_DIRECTORY})
SET (CTEST_BINARY_DIRECTORY ${CTEST_BINARY_TESTEXTERNAL_DIRECTORY})

SET (CTEST_PROJECT_NAME "OpenMS_external_code_test")

CTEST_EMPTY_BINARY_DIRECTORY (${CTEST_BINARY_DIRECTORY})

FILE(WRITE "${CTEST_BINARY_DIRECTORY}/CMakeCache.txt" ${INITIAL_CACHE})

CTEST_START (Nightly)
CTEST_CONFIGURE (BUILD "${CTEST_BINARY_TESTEXTERNAL_DIRECTORY}")
CTEST_BUILD     (BUILD "${CTEST_BINARY_TESTEXTERNAL_DIRECTORY}")
CTEST_TEST      (BUILD "${CTEST_BINARY_TESTEXTERNAL_DIRECTORY}")
CTEST_SUBMIT    (PARTS Configure Build Test)

restore_variables(required_variables)
